2024-11-30 21:26:44,350 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\NCH\Программирование\Python Project\Simple_Unit_Tests\tests_12_4.py", line 20, in test_run
    t_object = Runner(True)
               ^^^^^^^^^^^^
  File "C:\NCH\Программирование\Python Project\Simple_Unit_Tests\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-11-30 21:26:44,354 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\NCH\Программирование\Python Project\Simple_Unit_Tests\tests_12_4.py", line 10, in test_walk
    t_object = Runner('Флейморд', -15)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NCH\Программирование\Python Project\Simple_Unit_Tests\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -15
